/**
 * Represents the concept of Chemical Shift in NMR Spectroscopy.
 *
 * A Chemical Shift refers to the variation in the resonance frequency of a nucleus due to its electronic environment. This shift is
 * observed in an NMR spectrum and is measured in parts per million (ppm). The chemical shift provides insights into the chemical
 * environment of a nucleus, typically a hydrogen atom in 1H NMR spectroscopy.
 *
 * @typedef {Object} ChemicalShiftObject
 * @property {string} title - The title of the concept being discussed.
 * @property {string} description - A detailed description explaining the concept with examples.
 *
 * @type {ChemicalShiftType} ChemicalShiftType - An array of ChemicalShiftObject, holding all the details related to chemical shifts
 * in the context of NMR spectroscopy.
 *
 * @example
 * const chemicalShiftExample = {
 *   title: "Chemical Shift",
 *   description: "This spectrum of Ethanol illustrates the concept of chemical shift..."
 * };
 *
 * In this example, the chemical shift in a spectrum is described by how the atom's environment influences its magnetic field and
 * the resulting shift in the spectrum.
 *
 * The `ChemicalShiftData` provides a description and practical example of chemical shifts in the context of Ethanol's 1H NMR spectrum.
 * It explains the role of shielding and deshielding in determining the position of the peak, and how this relates to the chemical
 * environment of the hydrogen atoms in the molecule.
 */
interface ChemicalShiftObject {
  title: string; // The title of the concept
  description: string; // Detailed explanation and examples of the concept
}

type ChemicalShiftType = ChemicalShiftObject[]; // Defines the array structure of the chemical shift data

export const ChemicalShiftData: ChemicalShiftType = [
  {
    title: "Chemical Shift",
    description: `
      <p>This <button id="component-btn" data-id="1" class="underline inline text-[#A5C882]">spectrum of Ethanol </button> illustrates the concept of chemical shift.</p>
      <p>The location of each peak gives information about an atom’s environment, which is measured relative to a standard, Si(CH<sub>3</sub>)<sub>4</sub>, and is reported in ppm (which is Hz per MHz). This type of unit standardizes the location of a peak in a spectrum so that the size of the magnet (i.e. 270 MHz versus 400 MHz) does not matter—the location of that peak will be the same on any NMR instrument.</p>
      <p>Each nucleus will feel a local magnetic field generated by the electrons surrounding it in either bonds or lone pairs. This localized magnetic field will “shield” the nucleus from the much larger field of the magnet of the NMR instrument.</p>
      <p>Every hydrogen atom will feel the external magnetic field differently as a function of how shielded it is.</p>
      <p>Hydrogens that feel less of the external magnetic field are considered to be <button id="component-btn" data-id="2" class="underline inline text-[#A5C882]">shielded, which can also be referred to as upfield,</button> while hydrogens that feel more of the external magnetic field are considered to be <button id="component-btn" data-id="3" class="underline inline text-[#A5C882]">deshielded, which can also be referred to as downfield.</button></p>
      <p>The more deshielded (downfield) the atom is, the higher the absorbed frequency and the larger the chemical shift.</p>
      <p>This typical range of chemical shifts in a spectrum is from 0 to 12 ppm. This spectrum of Ethanol doesn’t showcase this entire range, but does show differences in chemical environment.</p>
      <p>Hydrogens on simple alkane carbons, such as those in <button id="component-btn" data-id="4" class="underline inline text-[#A5C882]"> purple (CH<sub>3</sub>),</button> will be located between 0 and 2 ppm. Hydrogens on a carbon next to an electronegative element, such as oxygen, will move downfield between 3 and 4.5 ppm, as seen by the <button id="component-btn" data-id="5" class="underline inline text-[#A5C882]">peak in pink (CH2).</button> The hydrogen on the oxygen, as shown in orange (OH), are dependent upon the sample and are seen between 0 and 5 ppm.</p>
      <p>Chemists refer to correlation charts that contain tables of typical 1H NMR chemical shifts. With a few essential guideposts, some understanding of polarity and experience with NMR spectra, chemists can make some educated guesses as to relative chemical shifts, even when they don’t have the correlation chart in front of them.</p>
    `,
  },
];
